routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great! 
|
*/
Route::get('/', 'HomeController@index');
Route::get('/post/{slug}', 'HomeController@show')->name('post.show');
Route::get('/tag/{slug}', 'HomeController@tag')->name('tag.show');
Route::get('/category/{slug}', 'HomeController@category')->name('category.show');
Route::get('/contact', 'HomeController@contact')->name('contact.show');
Route::post('/contact', 'SendFormMailController@send_form')->name('send.form');
Route::get('/about', 'HomeController@about');
Route::post('/subscribe', 'SubsController@subscribe');
Route::get('/verify/{token}', 'SubsController@verify');


Route::group(['middleware' => 'auth'], function (){
    Route::get('/profile', 'ProfileController@index');
    Route::post('/profile', 'ProfileController@store');
    Route::get('/logout', 'AuthController@logout');
    Route::post('/comment', 'CommentsController@store');
});

Route::group(['middleware' => 'guest'], function (){
  Route::get('/register', 'AuthController@registerForm');
  Route::post('/register', 'AuthController@register');
  Route::get('/login', 'AuthController@loginForm')->name('login');
  Route::post('/login', 'AuthController@login');
});



Route::group(['prefix' => 'admin', 'namespace' => 'admin', 'middleware' => 'admin'], function(){
  Route::get('/', 'DashboardController@index');
  Route::resource('/categories', 'CategoriesController');
  Route::resource('/tags', 'TagsController');
  Route::resource('/users', 'UsersController');
  Route::resource('/posts', 'PostsController');
  Route::get('/comments', 'CommentsController@index');
  Route::get('/comments/toggle{id}', 'CommentsController@toggle');
  Route::delete('/comments/{id}/destroy', 'CommentsController@destroy')->name('comments.destroy');

});


Route::get('/test', 'TestController@index');

resources/views/admin/_sidebar.blade.php
<ul class="sidebar-menu">
  <li class="header">MAIN NAVIGATION</li>
  <li class="treeview">
    <a href="#">
      <i class="fa fa-dashboard"></i> <span>Админ-панель</span>
    </a>
  </li>
  <li><a href="/"><i class="fa fa-home"></i> <span>Главная страница</span></a></li>
  <li><a href="{{route('posts.index')}}"><i class="fa fa-sticky-note-o"></i> <span>Посты</span></a></li>
  <li><a href="{{route('categories.index')}}"><i class="fa fa-list-ul"></i> <span>Категории</span></a></li>
  <li><a href="{{route('tags.index')}}"><i class="fa fa-tags"></i> <span>Теги</span></a></li>
  <li>
    <a href="/admin/comments">
      <i class="fa fa-commenting"></i> <span>Комментарии</span>
      <span class="pull-right-container">
              <small class="label pull-right bg-green">{{$newsCommentCount}}</small>
            </span>
    </a>
  </li>
  <li><a href="{{route('users.index')}}"><i class="fa fa-users"></i> <span>Пользователи</span></a></li>
  <li><a href="#"><i class="fa fa-user-plus"></i> <span>Подписчики</span></a></li>
</ul>

resources/views/admin/dashboard.blade.php
@extends('admin.layout')

@section('content')
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Привет! Это админка
        <small>приятные слова..</small>
      </h1>
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">Главная страница</h3>
        </div>
        <div class="box-body">
          Текст инструкции по пользованию админкой
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
          и здесь есть место для какого-нибудь текста
        </div>
        <!-- /.box-footer-->
      </div>
      <!-- /.box -->

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
@endsection

resources/views/admin/errors.blade.php
@if ($errors->any())
<div class="container" style="margin-top: 1rem">
  <div class="row">
    <div class="col-md-7">
      <div class="alert alert-danger">
      <ul class="ml30">
        @foreach ($errors->all() as $error)
        <li> {{$error}} </li>
        @endforeach
      </ul>
      </div>
    </div>
  </div> 
</div>
@endif